version: "3.8"
networks:
  my-bridge:
    external:
      name: my-bridge
services:
  auto-deploy:
    build: .
    image: ixuewen/auto-deploy
    container_name: auto-deploy-docker
    restart: always
    networks:
      - my-bridge
    volumes:
      - /var/docker-volume/auto-deploy/log:/root/log
      - /var/docker-volume/auto-deploy/data:/root/data
      - /var/docker-volume/auto-deploy/repo:/root/repo
      - /root/.ssh:/root/.ssh:ro
      - /etc/localtime:/etc/localtime:ro
      - /usr/bin/docker-compose:/usr/bin/docker-compose:ro
      - /var/run/docker.sock:/var/run/docker.sock
